version: "3.8"
services:
  grafana:
    build:
      context: .
    container_name: grafana
    ports:
     - '3011:3000'
    volumes:
     - 'grafana_storage:/var/lib/grafana'
     - './datasources:/etc/grafana/provisioning/datasources'
     - './dashboard-settings:/etc/grafana/provisioning/dashboards'
     - './dashboards:/var/lib/grafana/dashboards'
volumes:
    grafana_storage: {}
